### ISSUE TITLE
Module 13 Lab a/Ex 3/Task 3

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#19]
# Module: 13
### Task: 03

Role Assignment which we created in Exercise 1 task 2 still exists even after deleting the resource group. It can be viewed from other resource groups (or from subscription) by clicking on **Access Control IAM** blade. Kindly add instructions to remove it.

![Untitled](https://user-images.githubusercontent.com/49203962/90981633-af1ef080-e57b-11ea-9647-9cf072855b5c.png)

**Comment by polichtm** [comment]
Exercise 1 Task 2 involves configuring Reader role assignment on az30304a-labRG resource group - which is different from what your screenshot illustrates. Pls feel free to remove this assignment
rgds
Marcin
