### ISSUE TITLE
Module 13a/Exercise 3/task 1/ Step 5

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#20]
# Module: 13a
#### Step: 05

Third row of the table **System Topic Name** has already assigned value by default so unable to assign value provided in table.

![image](https://user-images.githubusercontent.com/49203962/90982183-ee9b0c00-e57e-11ea-893c-cbf53cee0d5b.png)

**Comment by polichtm** [comment]
updated
