### ISSUE TITLE
AZ-304 Module 1 Lab missing

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#22]
Trainer Prep Guide of AZ-304 mentions list of labs for this course but Module 1 Lab is missing in GitHub repository. I can find other labs though.

Module 1 Lab
• Lab Title: Implementing Containers on Azure
• GitHub filename: Module_1_Lab.md

**Comment by polichtm** [comment]
That's not a lab issue. Pls follow up on the MCT Forum
rgds
Marcin
