### ISSUE TITLE
Module 3/Exercise 2/task 1/Steps 11 and 12

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#25]
# Module: 03
#### Step: 11 and 12

Description of issue

11. On the **Configure Processor** page of the Import Virtual Machine wizard, set Number of virtual processors to 4, and select Next >.

12. On the **Connect Network** page of the Import Virtual Machine wizard, in the Connection drop-down list select NestedSwitch and select Next >.

Solution:
Above two steps are not part of **Import Virtual Machine Wizard**. Once this Wizard is complete then you can assign **number of virtual processors** and **Nested switch** by going to **settings** option of newly imported virtual machine.

![image](https://user-images.githubusercontent.com/49203962/91657531-189e8200-eadb-11ea-9e47-449064c34da7.png)

![image](https://user-images.githubusercontent.com/49203962/91657564-61563b00-eadb-11ea-9dac-6c448bdfeb21.png)

**Comment by polichtm** [comment]
That's incorrect. Pls make sure to import the VHD file
![image](https://user-images.githubusercontent.com/10284906/91664273-11b44700-eabc-11ea-894b-47365063e3f8.png)

rgds
Marcin
