### ISSUE TITLE
Please add a Note for Mod 3 Exercise 2

### ISSUE THREAD

**Issue by markturpinMSFT** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#29]
# Module: 03
#### Step: 03

Description of issue
Step 3:
"On the Discover machines blade, in the Name your appliance text box, type az30308a-vma1 and select the Generate key button."

Please add a note that mentions the student may have to assign their Azure AD account Owner/Contributor permissions to the subscription if they receive an error generating the key.  

If their account only has Service Administrator assigned on the subscription, it throws a permissions error.

**Comment by azharkhuwaja** [comment]
Agreed.

I added following note in my word doc file for lab instructions.

"Note: If you experience error while generating Azure Migrate project key, go to Azure Portal and click **Subscription**. Select **Access Control (IAM)** and then add **Role Assignment** as **Owner or Contributor** for your default account."

**Comment by polichtm** [comment]
updated 
rgds
Marcin
