### ISSUE TITLE
Connect to and query Azure SQL Database cannot be done like in exercise

### ISSUE THREAD

**Issue by mct370770** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#31]
# Module: 06
##Exercise: 01
#### Step: 03

Description of issue

From Azure Portal you cannot do the logon in step 3 - and thereby also not do step 4

Next part of exercise works

From Visual Studio you can logon - but that is not what is written

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updated
rgds
Marcin
