### ISSUE TITLE
There are references to AZ303 in the lab files reference that are confusing learners. Please update to reflect AZ304

### ISSUE THREAD

**Issue by mjeromeleonardGH** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#32]
# Module: Module 4: Design Authentication and Authorization
#### Step: 00

Description of issue
https://microsoftlearning.github.io/AZ-304-Microsoft-Azure-Architect-Design/Instructions/Labs/Module_4_Lab.html

There are 33 references to AZ303 labfiles in the AZ304 lab instructions
Lab Files
Objectives

\\AZ303\AllFiles\Labs\10\azuredeploy30310suba.json

Repro steps:

1. Review the instructions in all 3 tasks
1. Update the instructions and the file names in the zip package
1. Ensure there are no references to AZ303 left

**Comment by polichtm** [comment]
updated
