### ISSUE TITLE
Module 3 Task 2 Create an Azure Migrate project missing a value

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#34]
# Module: 03
#### Step: 02

![image](https://user-images.githubusercontent.com/24426530/93745397-0de09400-fc26-11ea-82b7-925f99c5b7a7.png)

Description of issue
 In the Azure portal, search for and select **Azure Migrate**, on the **Azure Migrate** blade, in the **Migration goals** section, select **Create Project**.

SHOUlD BE

. In the Azure portal, search for and select **Azure Migrate**, on the **Azure Migrate** blade, in the **Migration goals** section, select  **servers** and click **Create Project**.
Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updated
