### ISSUE TITLE
Source column is now called Directory synced

### ISSUE THREAD

**Issue by arnstrong** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#36]
# Module: 04
#### Step: 10

Description of issue
The source column is no longer available. But there is a column called Directory synced which contains the neccessary information.

Repro steps:

1. Go to All Users Page
1. Check available columns
![directory_synced](https://user-images.githubusercontent.com/444501/94005770-0c86a700-fd9f-11ea-9cb0-9d46d0d9a4d0.PNG)

**Comment by polichtm** [comment]
updated
