### ISSUE TITLE
Module 13 System Topic name | accept the default value |

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#38]
# Module: 13
#### Step: 05

Description of issue

 On the **Create Event Subscription** blade, specify the following settings and select **Create**:

    | Setting | Value | 
    | --- | --- |
    | Name | **event-subscription-az30304a-LabRG** |
    | Event Schema | **Event Grid Schema** |
    | System Topic name | accept the default value |

There is no default value for System Topic name.

![image](https://user-images.githubusercontent.com/24426530/94098193-b0815880-fe5a-11ea-92e5-c9fd55f8b640.png)

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updated
rgds
Marcin
