### ISSUE TITLE
Unable to complete LAB_08_Migrating to Azure.md

### ISSUE THREAD

**Issue by fisica3** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#4]
# Module: 00
#### Step: 4

Description of issue

Cannot complete the execution of the steps because configuration is not aligned to expected by script

Repro steps:

1. Follow all the steps until Excercise 1. Task 1. Step 3
2. Exectute the step 4, trying to run the related .ps, the first three checks go ok, but the "_Verifying Hyper-V Role is installed on the host..._" gets the message "**Hyper-V Role is not enabled. Exiting...**"

This unables to complete the remaining parts of the Lab.

**Comment by polichtm** [comment]
Hi Ernesto,
step 4 of task 1 in exercise 1 is contingent on the exercise 0 completed successfully. That exercise relies on a QuickStart template that provisions an Azure VM with nested virtualization enabled and the Hyper-V server role installed. Can you verify that this deployment completed successfully? Can you post the deployment details?
rgds
Marcin

**Comment by fisica3** [comment]
Yes the 0 step was completed, I had to delete the environment after the issue in order to avoid charges

**Comment by ElaMark** [comment]
Just for your information, I'm running the course this week with 20 students. Nobody reported an issue.

**Comment by polichtm** [comment]
I'm not able to reproduce this issue - I'm also seeing reports confirming that this lab works as expected. Pls give it another try and provide the deployment details if you run into this issue again
rgds
Marcin
