### ISSUE TITLE
Module_13_Lab_a refers to az-303

### ISSUE THREAD

**Issue by dpapkin** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#41]
# Module: 00
#### Step: 05

Description of issue
 In the toolbar of the Cloud Shell pane, select the **Upload/Download files** icon, in the drop-down menu select **Upload**, and upload the file **\\\\AZ303\\AllFiles\Labs\\04\\azuredeploy30304suba.json** into the Cloud Shell home directory.

SHOULD BE

 In the toolbar of the Cloud Shell pane, select the **Upload/Download files** icon, in the drop-down menu select **Upload**, and upload the file **\\\\AZ304\\AllFiles\Labs\\04\\azuredeploy30304suba.json** into the Cloud Shell home directory.

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
updated
rgds
Marcin

**Comment by azharkhuwaja** [comment]
Before exercise 0 in above lab, it mentions lab files location in which all are placed in **AZ 303** folder.

**Lab Files**
\\**AZ303**\AllFiles\Labs\04\azuredeploy30304suba.json

\\**AZ303**\AllFiles\Labs\04\azuredeploy30304rga.json

\\**AZ303**\AllFiles\Labs\04\azuredeploy30304rga.parameters.json

**Comment by polichtm** [comment]
updated

**Comment by azharkhuwaja** [comment]
Also steps 7 and 8 in above lab needs to be modified as well.

7. From the Cloud Shell pane, upload the Azure Resource Manager template \\**AZ303**\AllFiles\Labs\04\azuredeploy30304rga.json.

8. From the Cloud Shell pane, upload the Azure Resource Manager parameter file \\**AZ303**\AllFilesLabs\04\azuredeploy30304rga.parameters.json.
