### ISSUE TITLE
az group list command syntax error

### ISSUE THREAD

**Issue by bvenkataraman** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#42]
# Module: 06
#### Step: 01

Description of issue
az group list command syntax error
Repro steps:

1.az group list --query "[?starts_with(name, 'az30303')]**".name** --output tsv

results in ArgumentParseError: argument --query: expected one argument

This should be  

az group list --query "[?starts_with(name, 'az30303')]**.name"** --output tsv

**Comment by polichtm** [comment]
Pls make sure to use the Bash shell - not PowerShell, as per instructions
rgds
Marcin
