### ISSUE TITLE
HYPER-V Migration Lab - Cannot Generate Key 

### ISSUE THREAD

**Issue by uunrlg143** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#45]
# Module: 03
##### Step: 04

Description of issue: Unable to generate the key 

Repro steps:

1. Based on the Step 4 of the instruction, i enter the applicance Name and click on generate key. 
 -  I get the error deployment failed. 
 - I am using LabonDemand. 
 - I have given myself the owner permission as per the instructio. 
![JSON scritp](https://user-images.githubusercontent.com/40092890/101321585-963d0100-3833-11eb-8271-56c9c0eb4e5b.PNG)

**Comment by polichtm** [comment]
Have you tried signing out and signing back in before proceeding?
Would you mind giving it another try? 
rgds
Marcin

**Comment by polichtm** [comment]
Closing due to lack of response
