### ISSUE TITLE
Set-MsolDirSyncEnabled : You cannot turn off Active Directory synchronization

### ISSUE THREAD

**Issue by mhykgyver** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#46]
# Module: 04
#### Step: 08

Description of issue
Set-MsolDirSyncEnabled : You cannot turn off Active Directory synchronization 

Referencing the ff. articles in regards to this issue:

https://community.spiceworks.com/topic/2150414-disable-azure-ad-connect-via-powershell
https://www.michev.info/Blog/Post/1797/you-cannot-turn-off-active-directory-synchronization

Repro steps:

1. run Set-MsolDirSyncEnabled -EnableDirSync $false -Force and you'll get the error listed above

**Comment by polichtm** [comment]
updated
