### ISSUE TITLE
AZ-304 Module 4 Lab Step Issues

### ISSUE THREAD

**Issue by JeffSmalley** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#47]
# Module: 04
## Lab/Demo: 00
![Exercise 2 Task 4 Old Layout](https://user-images.githubusercontent.com/16696370/102302871-9027de00-3f1f-11eb-8399-1f240e1644cb.png)
![Exercise 2 Task 4 New Layout](https://user-images.githubusercontent.com/16696370/102302873-90c07480-3f1f-11eb-8956-6a594fa68310.png)
![Exercise 3 Task 3 Redirected URL](https://user-images.githubusercontent.com/16696370/102302874-90c07480-3f1f-11eb-8a5e-7eccb0210163.png)

#### Step: 00

Description of issue
Exercise 2, Task 2 
A new step 1 needs to be added to instruct students to switch back to the original Azure Active Directory (Tenant).
The previous Task 1 ends with working in the new tenant Adatum Lab.

Exercise 2, Task 4, step 2: It looks like the portal interface has changed. There is no column called "Source" anymore. I added a picture of the old interface and a picture of the new interface.

Old Statement
On the Users All users blade, note that the list of user objects includes the aduser1 account, with the Windows Server AD appearing in the Source column.

New proposed statement:
On the Users All users blade, note that the list of user objects includes the aduser1 account, with the Yes indicator in the Directory synched column.

Exercise 3, Task 3, Step 1  Replace to new URL. The old URL just redirects to new URL.
Old URL  https://account.activedirectory.windowsazure.com
New URL  https://myapplications.microsoft.com

I added a picture of the redirected website destination

Repro steps:

1.
1.
1.

**Comment by polichtm** [comment]
Hi Jeff,
updated
rgds
Marcin
