### ISSUE TITLE
Minor issue related to the name of the replicated machine

### ISSUE THREAD

**Issue by pavlovmilen** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#49]
# Module: 03
#### Step: 09 and 10

Description of issue
Minor issue related to the name of the replicated machine
Repro steps:
In Module 3, exercise 3, task 3 steps 9 and 10 it says **az30307a-vm1** and it should be **az30308a-vm1**

**Comment by polichtm** [comment]
updated
rgds
Marcin
