### ISSUE TITLE
Lab for Module 1 is missing 

### ISSUE THREAD

**Issue by Frank-Geisler** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#55]
# Module: 01
## Lab/Demo: 01

In the slide deck there is a slide that points to a Lab for module 1:

#### Tasks:
   - Implement containers running in Azure VMs
   - Deploy containers to Azure Container Instances
   - Deploy containers to Azure Kubernetes Service (AKS) clusters
  
It seems that this lab is missing in this repository.

Thank you very much and have a nice day

Frank

**Comment by polichtm** [comment]
Hi Frank,
appreciate pointing this out. We'll follow up regarding updating the content
rgds
Marcin

**Comment by ElaMark** [comment]
When the course was first put together it was in there, and then taken out. For me that was a good thing as i found there was too much material in the course and not enough time to get through it.

**Comment by Frank-Geisler** [comment]
Hi ElaMark! That is not the point. The point is that there are references in the slide deck. To be consistent either the module should be added or the slide should be deleted.

**Comment by polichtm** [comment]
Hi Frank,
pls refer to the MCT forum regarding this request. This repo is intended for updates to the labs, rather than the course
rgds
Marcin
