### ISSUE TITLE
Vm1notavailableinreplicateblade

### ISSUE THREAD

**Issue by billwood44** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#61]
# Module: 03
#### Step: 3

Description of issue

I followed all of the steps, in the lab for exercises 1 and 2.  When I get to the replicate VM task, az30308a-vm1 is not in the list of VM's that can be replicated.  As a matter of fact, there are no VM's listed.  Not sure what the issue is.  The Discover tile of Azure Migrate shows VM1 in the Assessment Groups, and that indicates an issue with VM1, but those steps were not in the instructions. 
![Module03Ex3Task2Step3_reasonvm1notshowinginreplicatescreen](https://user-images.githubusercontent.com/16070952/111088246-aa606080-84fc-11eb-8004-2323f61d5cab.PNG)
![Module03Ex3Task2Step3_vm1notavailalbeinreplicationwizard](https://user-images.githubusercontent.com/16070952/111088251-ad5b5100-84fc-11eb-9053-9c2e7e1704ec.PNG)

Repro steps:

1.
1.
1.

**Comment by billwood44** [comment]
After running through the lab again.  It appears I was just not patient enough to wait for the discovery process to complete.  Running the lab a second time and waiting the requisite 15 minutes (as mentioned in the lab), everything worked as written.

**Comment by polichtm** [comment]
appreciate the clarification
rgds
Marcin
