### ISSUE TITLE
Lab 13: ServicePrincipal missing access to write events from ResourceGroup into EventGrid

### ISSUE THREAD

**Issue by abij** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#63]
# Module: 13
#### Step: 04

Issue: ServicePrincipal with **Reader** on the Resource Group results in error: No permissions to perform action Microsoft.EventGrid/eventSubscriptions/write

When the LogicApp (trigger) is created, there is a **Failure** in LogicApp -> Overview -> Trigger History. The failure can be clicked. The Output Link can be clicked.

Detail error:

```
{
    "statusCode": 403,
    "headers": {
       // lots of headers 'n stuff
    "body": {
        "error": {
            "code": "AuthorizationFailed",
            "message": "The client '665cf86d-d4de-4b6a-b4df-*******' with object id '665cf86d-d4de-4b6a-b4df-*******' does not have authorization to perform action 'Microsoft.EventGrid/eventSubscriptions/write' over scope '/subscriptions/***/resourceGroups/abij-playground/providers/Microsoft.EventGrid/eventSubscriptions/event-subscription-abij-playground' or the scope is invalid. If access was recently granted, please refresh your credentials."
        }
    }
}
```

I have solved issue bij granting the ServicePrincipal additional access right to the resource group, role: **EventGrid Contributor**. But I'm not sure if the access scope can be more narrow.

**Comment by polichtm** [comment]
Hi Alexander,
pls provide the exercise, task, and step number you are referring to - along with the repro steps.
Btw. it appears that you are using your own naming convention...
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
