### ISSUE TITLE
"dnsPrefix" missing in azuredeploy30410rga.parameters.json?

### ISSUE THREAD

**Issue by jmanuelng** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#65]
# Module: 04
#### Step: 07

Description of issue
"Edit Parameters error"

Repro steps:
1.- On the Edit parameters blade, select Load file, in the Open dialog box, select \\AZ304\AllFiles\Labs\10\azuredeploy30410rga.parameters.json, select Open, and then select Save.

My solution:
Manually edited parameters based on azuredeploy30410rga.parameters.json file. I noticed the following is missing on that JSON file

    "dnsPrefix": {
      "value": null
    },

Hope this helps.

**Comment by polichtm** [comment]
Would you mind providing a screenshot of the error you are referring to?
The dnsPrefix parameter should be populated during template deployment - so it's not included in the parameters file.
rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
