### ISSUE TITLE
There is no instructions for Lab 1 

### ISSUE THREAD

**Issue by rlopezgarcia** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#66]
Module: 01
Lab/Demo: 01

Description of issue
No instructions for La 1 (Implementing Containers on Azure)
Repro steps:

1. Open Github Repo for this course
1. Click on Instructions/Labs
1.

**Comment by polichtm** [comment]
Pls post this inquiry on the MCT forum
rgds
Marcin

**Comment by polichtm** [comment]
To be managed/tracked via a separate channel
rgds
Marcin
