### ISSUE TITLE
Module 4 Exercise 3 Task 4 Step 8: Turn off AD sync (fails)

### ISSUE THREAD

**Issue by LodsCory** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#74]
# Module: 04
#### Step: 08

Description of issue
When you try to turn off Active directory synchronization it fails. Instead of turning off AD sync it seems to be just as effective to suspend it.

There is a note in the instruction warning of this failure. Would it be a good idea to add that the user may choose to suspend?

Repro steps:

1. Run command Set-MsolDirSyncEnabled -EnableDirSync $false -Force
1.
1.

**Comment by polichtm** [comment]
Could you clarify what you mean by "suspend"?
Pls provide a screenshot of the error message you're seeing when running the command you are referencing
rgds
Marcin

**Comment by LodsCory** [comment]
In Module 4, Exercise 3, Task 4, Step 8 you are asked to disable the Azure AD Connect Synchronization by running the command "Set-MsolDirSyncEnabled -EnableDirSync $false -Force". When you do you get the error:
![image](https://user-images.githubusercontent.com/62734074/119756003-e3a83b80-be70-11eb-8a2a-2d29247b49f7.png)

There is a note in the instructions about this saying that if you get this error you might have to wait 12 hours and try again:
![image](https://user-images.githubusercontent.com/62734074/119756129-18b48e00-be71-11eb-841a-ad260468cf42.png)

My apologies about the "suspend" statement. I thought you could suspend the current AD sync operation by executing the command "Set-MsolDirSyncEnabled -EnableDirSync $true" then selecting "[s]Suspend" when prompted to continue, but you cannot. 

Given that, the 72 hour wait period appears to make step 8 null. You can continue with the lab without issue. I wonder if it's worth just removing that step all together to avoid confusion. I also had the the thought that it could it be moved to the end of the lab just for reference.

**Comment by polichtm** [comment]
Here is step 8:
In the Administrator: Windows PowerShell window, run the following to disable Azure AD Connect synchronization:

Set-MsolDirSyncEnabled -EnableDirSync $false -Force
Note: If you receive an error message at this point, you might have to wait for up to 12 hours and try again.

Could you clarify what you mean by "Given that, the 72 hour wait period appears to make step 8 null. "?
rgds
Marcin

**Comment by LodsCory** [comment]
The lab says 12 hours but Microsoft, in their docs says 72 hours. In testing it looks like 72 hours is more accurate. Either way, 12 hours or 72 hours, I don't think students are going to wait that long to complete a step that doesn't effect the rest of the lab. I think it would reduce confusion and make the user experience better if the step were shifted to the end of the lab, made into a note for reference, or removed all together.

**Comment by polichtm** [comment]
Appreciate the suggestion, but pls keep in mind that these instructions are not part of the lab. You're welcome to use them if you choose to do so - but they are optional. They are provided in case someone chooses to follow them.
More importantly, you won't be able to continue with these instructions unless this step is completed (there will be user accounts which are synchronized from AD)
rgds
Marcin
