### ISSUE TITLE
Quickstart template VMs do not have edge

### ISSUE THREAD

**Issue by LodsCory** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#75]
# Module: Multiple
#### Step: 00

Description of issue
In multiple modules you are asked to go to GitHub and use a quickstart template to provision a VM. The image called in the quickstart template does not have edge installed, and when the user attempts to install edge they get an app error.

Now that IE is no longer compatible with Azure portal Edge is needed to perform most of the lab. Can we add the edge installer to the lab files and add instructions to copy the installer to the quickstart VM once its provisioned? If thi sis suitable I can create the pull request if you would like?
Repro steps:

1. Within the Remote Desktop session to az30410a-vm1, start Internet Explorer, navigate to the download page of Microsoft Edge, download [Microsoft Edge](https://www.microsoft.com/en-us/edge/business/download) installer and perform the installation.
1. Installation fails
1.

**Comment by polichtm** [comment]
Pls provide the lab, exercise, task, and step number(s) you are referring to 
Btw. what specifically do you mean by "installation fails"? Pls provide a screenshot illustrating the error message you're seeing.
rgds
Marcin

**Comment by LodsCory** [comment]
There are multiple modules that have you provision a VM in Azure using a quickstart template from GitHub, but one example is Module 4, Exercise 2, Task 3, Step 1. The web page listed is correct, but it seems that users are getting stuck on that download page. We have had a couple ESI users get stumped here. My thought was to either add the installer to the lab files so they can copy it to the VM created with the quick start template labeled az30410a-vm1. Or, we could add the following steps to the instructions:

1.  Within the Remote Desktop session to az30410a-vm1, start Internet Explorer, navigate to the download page of Microsoft Edge, download [Microsoft Edge](https://www.microsoft.com/en-us/edge/business/download).
2. In **Select channel/version** dropdown select the version indicating **Stable ## (Current and supported)**.
3. In **Select build** dropdown select the newest build.
4. In **Select platform** dropdown select **Windows 64-bit**.
5. Click **Download**

If they don't do this and click the link at the top it leads them to a download link that gives the error below:
![image](https://user-images.githubusercontent.com/62734074/119750657-c458e080-be67-11eb-843a-80cdb5ea6c4e.png)


I can create the pull request with this change if you would like?

**Comment by polichtm** [comment]
What specifically are you trying download? It appears that this a *.pdf file.
Here is what I'm seeing (there are no issues with download/install):

![image](https://user-images.githubusercontent.com/10284906/119806418-2e957380-beb0-11eb-9d12-dbeae3eaaf8e.png)

rgds
Marcin

**Comment by LodsCory** [comment]
That error is only if the user clicks the link at the top of the web page and doesn't scroll down. I created a pull adding additional instruction that I think will eliminate confusion. https://github.com/MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design/pull/78
