### ISSUE TITLE
Download no longer exists

### ISSUE THREAD

**Issue by shanecribbs** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#76]
# Module: 04
#### Step: 1

"Microsoft Edge and browse to the Microsoft Online Services Sign-In Assistant for IT Professionals RTW" download no longer exists.  Is it necessary?  Has it been replaced?

**Comment by LodsCory** [comment]
This link is now broken. When users go to the link in the instructions, [https://www.microsoft.com/en-us/Download/details.aspx?id=28177](https://www.microsoft.com/en-us/Download/details.aspx?id=28177) they are directed to this page 
![image](https://user-images.githubusercontent.com/62734074/119751645-8b217000-be69-11eb-99c6-773f7dd9bbc6.png)

I found the installer here https://download.microsoft.com/download/7/1/E/71EF1D05-A42C-4A1F-8162-96494B5E615C/msoidcli_64bit.msi. We could change the link, or the installer could be added to the lab files and copied when needed to the **az30410a-vm1** (installer below).

[msoidcli_64bit.zip](https://github.com/MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design/files/6550494/msoidcli_64bit.zip)

**Comment by LodsCory** [comment]
I created a pull request if you decide that changing the link is the best route https://github.com/MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design/pull/77. 

I do think it may be a good idea add the installer to the lab files instead.

**Comment by polichtm** [comment]
updated
