### ISSUE TITLE
Module 13a

### ISSUE THREAD

**Issue by azharkhuwaja** [MicrosoftLearning/AZ-304-Microsoft-Azure-Architect-Design#80]
# Module: 13
#### Step: 01

Following line should be modified:
In the Azure portal, navigate to the az30304b-logicapp1 blade, in the Summary section, select Trigger history.

As "Summary" section doesn't exist anymore so please modify it as follows:
In the Azure portal, navigate to the az30304b-logicapp1 blade, select Trigger history.

**Comment by polichtm** [comment]
updated
